### ISSUE TITLE
separate IO from the rest of the code

### ISSUE THREAD

**Issue by anna-hope** [lxa2015/lxa-py#1]
I think we should separate the code in which we read in the corpus/ngrams from the rest of the code. 

Aside from making the code easier to manage, this would allow us to use the corpus reading code from other modules, for instance my stem alternation module. Separating that code should also make it easier to adapt the engine to be used with a GUI because the GUI version would have to be separate from the CLI functions anyway.

If everyone (mainly Jackson) is okay with this, I'll make the necessary changes.

**Comment by jacksonllee** [comment]
Sounds great to me!

**Comment by anna-hope** [comment]
done
