### ISSUE TITLE
input corpus filename

### ISSUE THREAD

**Issue by anna-hope** [lxa2015/lxa-py#3]
I have noticed that the create_wordlist function now forces the input file to end in _words.txt. Is there a reason for this to be hardcoded?

I think that this behaviour is opaque, i.e., the user would not know that they are doing something wrong until they run into an error message (and even then it might not be very obvious why there is an error involving a _words.txt file when the user clearly specified a different filename). 

Aside from this opaqueness, having this behaviour hardwired into the code makes it more difficult to use the lxa5 module from the outside, as a library. For instance, I need some lxa5 functions for my part of the project, and the filenames I use don't follow this _words.txt convention. 

I think that we should remove this hardcoded part, and make the module's functionality more explicit and therefore less likely to cause confusion or errors.

**Comment by jacksonllee** [comment]
This behavior follows from the (current) assumption that the ultimate raw data is a raw text (not a wordlist). The n-gram files (_words.txt, _bigrams.txt, _trigrams.txt in the "ngrams" subfolder inside the "data" folder) are derived from another tool (to be incorporated in this repository very soon) which "knows" how to name the ngram files. Given your question, it is clear that we need to allow for the possibility that the user has, say, a wordlist but not a raw corpus to work with, and that the wordlist can be specified in the command line if nothing with the "expected" filename/path is found. A fix will be up real soon -- ideally one that will work for both non-GUI and GUI use.

**Comment by anna-hope** [comment]
Please see https://github.com/lxa2015/lxa-py/commit/7f6a776f1127ae22f1b07653982e73b016024e88 for a proposed replacement. My fix allows for an arbitrary filename to be specified explicitly, and so whatever tool needs to use the corpus-building function can specify any filename it needs, following whatever internal conventions it has. (In addition, my re-written function allows to specify for a maximum number of words to be extracted from a corpus, following our discussion with @JohnAGoldsmith).

If you have no objections to my proposed update, I will merge it into the current branch.

**Comment by jacksonllee** [comment]
I am now looking at the create_wordlist function in lxa5.py in your stemalts branch.

Do you assume that filename in create_wordlist doesn't end with ".txt" (which entails that the variable corpus in the main function doesn't have ".txt" either)?

The way the max number of words is implemented does not seem to be what is desirable: if max_words is n, the current code randomly picks n word types from word_freq_dict, which does not respect the type-token word distribution properties in natural languages. What we mean by having a cap for max number of words is that only n word _tokens_ from a raw text (not a wordlist) are read. It seems that this step of imposing a max cap should really be part of the ngram generator (already created and being augmented/fixed for all current coding conventions) that derives the ngrams from a raw text -- I'll get this up as soon as I can.

**Comment by anna-hope** [comment]
Sorry, I referenced the wrong commit (it should have been https://github.com/lxa2015/lxa-py/commit/9e36b89587b6edf7c2bb9a95cec6e0a5c76fa6c4, but it seems you found it anyway!)

You are correct, my version of the function assumes nothing about the filename, including its extension. This is deliberate: a given file could have any extension (txt, dx1, or even no extension at all, as some wordlists out there) and, as long as the file itself is structured in a way that our program can process, that file should be accepted – regardless of its name or extension.

**Comment by anna-hope** [comment]
Apropos the maximum number of words: it's entirely possible I misunderstood the objective. If so, I will remove that part of the code.

**Comment by anna-hope** [comment]
I've removed the max words code (https://github.com/lxa2015/lxa-py/commit/8467665a10ce4ccdd8d3f61c84b62f61e33b3ccb). Also, I made some internal changes to the lxa5_module function which returns a dictionary of word frequencies (see https://github.com/lxa2015/lxa-py/commit/4b3b6529f18920c5e33119fd87c5527914d0b40e).

**Comment by jacksonllee** [comment]
Looks great! Please feel free to merge them to the master branch.
