### ISSUE TITLE
a general module for commonly used functions etc?

### ISSUE THREAD

**Issue by jacksonllee** [lxa2015/lxa-py#5]
As more core components are added to this repository, several bits of code keep being reused across them. This means making changes to them is increasingly a pain in the neck. It seems desirable to factor these out and put them in a module (call it `lxa_util.py` or whatever) that can be imported and shared by all core components. The following snippets of code are good candidates to be put inside such a module (very likely there are more to come):
- the function `load_config`
- the function `json_pdump` 
- the function `changeFilenameSuffix`
- the snippet that reads the parameters for `language`, `corpus`, and `datafolder` and ensures the existence of the corpus file

(Some of these are in `phon.py` from [this commit](https://github.com/lxa2015/lxa-py/commit/2a84a27258de3cca92c4cab412035e5056d20de3))

If everyone is happy with this, I'll go ahead and implement this change (while making sure that nothing for the command line usage or anything else breaks).

**Comment by anna-hope** [comment]
I was going to propose something similar, like an lxa5lib module, so it's a yes from me.

**Comment by jacksonllee** [comment]
done!

**Comment by JohnAGoldsmith** [comment]
Great --
