### ISSUE TITLE
OutputLargeDict2

### ISSUE THREAD

**Issue by jacksonllee** [lxa2015/lxa-py#6]
I didn't notice there's the new function `OutputLargeDict2` in `lxa5_module.py` until just now when I tried to run the latest version of `lxa5.py` and `lxa5_module.py`. The program seems to be stuck (infinite loop?) or something at this line when `OutputLargeDict2` is called: https://github.com/lxa2015/lxa-py/blob/master/lxa5.py#L173
A quick fix from those working on this function ( @notnami ? @JohnAGoldsmith ?) would be great -- I'm trying to get the signature transforms and other things.

**Comment by anna-hope** [comment]
Hi Jackson,

It doesn't get stuck on my machine. I rewrote the function so that it now prepares all the output before it writes it out to a file, so you might have to wait a bit before it goes through, but it should continue eventually. 

Let me know if there's still a problem and I'll have a look at. I'm not done working on that part of the code, so I'll be changing some things anyway. 

Anton

**Comment by jacksonllee** [comment]
Ah, I see. I've just tried to run it again and let it do the work. but the program got stuck at the same point and killed itself after several minutes. Now I'm using the older function `OutputLargeDict` that I wrote before (code still there in `lxa5_manifold.py`) and the whole program takes less than 3 seconds to finish and output everything. Question: What is the purpose of `OutputLargeDict2`? If we want prettier output format, do you guys think we could simply just use a tab as the separator (and view the output with a spreadsheet program), without the hassle of having to compute how many spaces to use for every single cell?

**Comment by jacksonllee** [comment]
`lxa5_module.py`, not `lxa5_manifold.py`

**Comment by JohnAGoldsmith** [comment]
Yes, as you say, the purpose is to make the output more readable, but no,
opening a spreadsheet is not a good alternative. Calculating the spaces
shouldn't cause a significant difference in running time, though. I suspect
if you take that part out (use 1 space rather than computing the number of
spaces) it won't change the run time. There must be a something else
responsible for the time (...just my hunch). I did not have a problem with
it when I wrote it, though.  (Still, your concern is exactly why we need a
set of regression files, and we should ask Valeria to include time of
running as well as output...)
John

**Comment by anna-hope** [comment]
The OutputLargeDict2 function was originally written by John, who wanted to change the output. My original intent was to fix how the lxa sorts the affixes in the output, but also to clean up the code while doing that. 

It's possible that we don't need two functions doing essentially the same thing (and indeed that would make the code simpler and easier to follow), but you and John should decide that. Perhaps the solution would be, as you said, to modify the way output is presented by the original OutputLargeDict function. 

Anton

**Comment by jacksonllee** [comment]
John -- If, as you said just now, we can simply use 1 space rather than having to compute how many spaces for every single cell, then we can definitely do this and this will save a huge amount of computation (finding longest entry in each column etc); in fact, the older `OutputLargeDict` function is already doing this.

Now that I'm reading the code for `OutputLargeDict2` more closely, I notice something else that John was trying to do. Instead of outputting a signature like `("NULL", "s", "ed", "ing)` in the output text file, the preferred format is `NULL-s-ed-ing`. This seems to be the key difference between `OutputLargeDict` and `OutputLargeDict2` (modulo the spaces, cf. previous paragraph).

To move forward, I will now do the following:
- modify `OutputLargeDict` for the better signature output format. 
- use `OutputLargeDict` throughout (instead of `OutputLargeDict2`) in `lxa5.py`
- keep the code of `OutputLargeDict2` in `lxa5_module.py` for now

After I push the updates to the repository, I will post here again. Anton -- please check out the result afterwards and see if refactoring/optimization is needed.

**Comment by jacksonllee** [comment]
`OutputLargeDict` in `lxa5_module.py` is now modified and used in `lxa5.py`. Changes done:
- signature output format is like `NULL-s-ed-ing` rather than `("NULL", "s", "ed", "ing")`
- with the help of `itertools.zip_longest`, I decided to put in the spaces for the more aligned output format

I ran `lxa5.py` on the entire Brown corpus and it took around 2 to 3 seconds to finish and output all the text files -- seems reasonable to me, though possibly things could be optimized.

Please check if the latest output format is desirable.

**Comment by jacksonllee** [comment]
One more thing -- `OutputLargeDict` outputs a dict such as it is sorted not only by the size of the values, but also alphabetically by the keys whose share the same size. Hopefully this helps eliminate spurious differences when we run regression etc

**Comment by anna-hope** [comment]
Great. 

Anton

**Comment by jacksonllee** [comment]
A final remark as I'm closing this ticket on github: `OutputLargeDict` has now been moved to `lxa5lib.py` (it was in `lxa5_module.py` previously ), as this function is possibly useful for other modules as well. The function `sorted_alphabetized` (used by `OutputLargeDict` and `json_pdump`) is also in `lxa5lib.py` as well .
