### ISSUE TITLE
standardise JSON output

### ISSUE THREAD

**Issue by anna-hope** [lxa2015/lxa-py#7]
As @JacksonLLee probably knows, the way linguistica currently serialises its results into JSON is somewhat ad-hoc. In most cases, we just create string representations of Python objects and write those into JSON as-is. Although this may be a convenient temporary option while we concentrate on other, more conceptually challenging parts of linguistica, this approach removes most benefits of using JSON: JSON works best as a portable, language-agnostic format, which can help us use linguistica's results across a variety of other programs (which may be written in Python, C++, or any other language). However, with the current approach we generate output that can only be deserialised with Python and, more importantly, may vary dramatically based on the kind of data that output represents given our undocumented internal conventions. 

I think that the sooner we begin to standardise our output, the less 'tech-debt' we will have later and the easier it will be to fix whatever issues may arise with the eventual standardisation. (It so happens that my part of the project depends on working with linguistica's output, so I have my own vested interest in making that output easier to process).

I see the work as consisting roughly of 4 parts:
1. Make a list of every kind of object that linguistica currently puts into JSON so that we may come up with the best way of representing it in the JSON standard. This brings me to the following question: If I run linguistica on, say, the Brown corpus, would the JSON files generated as a result of that contain every kind of object that we aim to cover in the foreseeable future? That is, do we expect to be serialising any other objects not included in the output of the current version?
2. Create a sort of wrapper library which would be responsible for reading and writing our new standardised JSON output. We would be able to call this library from linguistica pretty much the same way we call the json_pload and json_pdump functions now — except on the inside this library will make sure that the JSON output is readable, portable, and consistent. I believe that we should write a function for serialising JSON first — that way, we reduce the possibility that something breaks in any of linguistica's critical parts. Also — please correct me if I'm wrong — other than for the config file, linguistica itself does not depend on reading JSON, so I don't see improving the reading of JSON as a current priority.
3. Test that everything works, and that the main parts of linguistica continue to work as before. 
4. Describe and document the resulting output format as part of this project's ReadMe so that anyone using linguistica could work with its output without having to go deeper into how our code actually works.

If @JacksonLLee and everyone else considers this a worthwhile cause, I can start working on this. Despite the length of this issue post, I don't see this part of the project as particularly complicated, so I should be able to complete it by myself without taking too long. Of course, I would welcome suggestions and any potential help from other members of our group, so let me know what you think.

**Comment by jacksonllee** [comment]
Thanks for the note! A while ago I also noticed the potential issues with ad hoc `json_pdump` and `json_pload` down the road and have in fact been deprecating (and removing) them in the latest code in the "gui-test" branch. (This is the branch I've been working on recently, not the "master" branch; the master branch will be updated after @JohnAGoldsmith has thoroughly reviewed the code in "gui-test".) Currently, the remaining places in the "gui-test" code where `json_pdump` and `json_pload` are still used are where things are under development. These two ad hoc functions will be completely gone very soon.

**Comment by anna-hope** [comment]
Ah, I didn't look in the gui branch. Right.

I've checked it out and I have a couple of questions.

1) Is there a reason for not setting the indent to something like 4 as a default argument? To be sure, it doesn't matter if the input is going to be read by a machine, but it would help with human readability.

2) This concerns in particular the output of _SigToStems: I see that the signatures in the keys are not separated very clearly, so you get something like ""'s-NULL-n-ns" which may be difficult to parse. May I propose we add a separator (perhaps a '/') so that the output can be parsed more easily?

**Comment by jacksonllee** [comment]
1. All (or almost all?) JSON outputs have a corresponding customized text output for humans and for the most part we don't really have to view the JSON files ourselves. Perhaps that's why I picked the most compact JSON representation, though I imagine we might possibly want to inspect the JSON outputs for debugging or other purposes. Maybe in my next push update, the indent argument could be set to some positive integer.
2. The affixes in any given signature are sorted (to ensure the uniqueness of the signatures), so any signature that contains an affix beginning with an apostrophe (= the single quote) will almost certainly have this affix as the _first_ affix (e.g., 's-s, 's-NULL, etc). So far I haven't run into any parsing issues regarding this. Any comments from @JohnAGoldsmith and others?

**Comment by anna-hope** [comment]
1. In my working copy, I currently have the indent set to 4 (which is usually the most convenient indent level). I can push that to the repository. I do think that JSON should be pretty-printed because there may be projects which require working with the JSON output (and not the printed signatures from the .txt files), such as the project I'm working on now.
2. I don't understand how sorting should help with uniqueness. My impression was that it's the signature tokens (i.e. -s or -ed) that matter, not the order in which they occur. Is it ever the case that we have two or more signatures consisting of the same tokens, but in different order? (Perhaps it is, I just don't know). 

"any signature that contains an affix beginning with an apostrophe ... will almost certainly have this affix as the first affix" This is what I find difficult. A parser for linguistica's signatures must be language-agnostic, and thus cannot rely on any sorting order (essentially, it must treat every signature as an orderless collection such as a set — hence my question above). It also cannot rely on 'knowing' that some signature may be present or absent. But this is somewhat off topic right now.

As to the issue of separators, I suppose I can use the '-' from linguistica's signatures as an implicit separator when parsing signatures, and, at least in Python, this will work. But relying on something implicit is what I wanted to avoid, which is why I suggested we add an explicit separator for signatures.
